services:
  frontend:
    container_name: flavormate_webapp
    image: ghcr.io/flavormate/flavormate-webapp
    restart: unless-stopped
    environment:
      - BACKEND_URL=https://example.com
    ports:
      - 8080:8080
    healthcheck:
      test: [ "CMD-SHELL", "curl -so /dev/null http://localhost:8080/ || exit 1" ]
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 5s
