# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new release build to Testflight"
  lane :deployTestflight do
    output_directory = "build/appstore/"

    setup_ci if ENV["CI"]

    app_store_connect_api_key(
      duration: 1200,
      in_house: false,
      is_key_content_base64: true,
    )

    match(type: "appstore", readonly: true)

    build_app(workspace: "Runner.xcworkspace", scheme: "Runner", output_directory: output_directory)

    upload_to_testflight(
      skip_waiting_for_build_processing: true,
    )
  end

  desc "Build a new test build"
  lane :buildTestBuild do
    output_directory = "build/appstore/"

    setup_ci if ENV["CI"]

    app_store_connect_api_key(
      duration: 1200,
      in_house: false,
      is_key_content_base64: true,
    )

    match(type: "appstore", readonly: true)

    build_app(workspace: "Runner.xcworkspace", scheme: "Runner", output_directory: output_directory)
  end
end
